FROM node:18-alpine
# FROM keymetrics/pm2:18-alpine

WORKDIR /usr

RUN npm install pm2 -g

# RUN pm2 install pm2-logrotate

COPY package.json ./
COPY pm2.json ./

RUN npm install --omit=dev

COPY ./dist/ ./dist/

ARG PORT=5000
EXPOSE ${PORT}

CMD [ "pm2-runtime", "start", "pm2.json" ]